import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import Link from "next/link";
import { cookies } from "next/headers";
import { logout } from "./logout";


export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const token = cookieStore.get('token')?.value;
  const isLoggedIn = token !== undefined;

  return (
    <html lang="en">
      <body className="container mx-auto">

        <header className="mb-10 flex items-center justify-between px-4 py-4 border-b border-gray-200">
          <Link href="/">
            <span className="text-xl font-bold text-gray-800">📚 Next Library</span>
          </Link>
          <nav className="flex items-center gap-6 text-sm text-gray-600">
            <Link href="/" className="hover:text-gray-900 transition-colors">Home</Link>
            {isLoggedIn ? (
              <>
                <Link href="/manage/book" className="hover:text-gray-900 transition-colors">
                  Manage Books
                </Link>
                <form action={logout}>
                  <button className="bg-gray-100 hover:bg-gray-200 text-gray-700 px-4 py-1.5 rounded-lg transition-colors">
                    Logout
                  </button>
                </form>
              </>
            ) : (
              <Link
                href="/login"
                className="bg-gray-800 hover:bg-gray-700 text-white px-4 py-1.5 rounded-lg transition-colors"
              >
                Login
              </Link>
            )}
          </nav>
        </header>

        {children}

        <footer className="mt-10 flex items-center justify-between px-4 py-4 border-t border-gray-200 text-sm text-gray-500">
          <span>© 2026 Next Library</span>
          <span>Made with Next.js & Tailwind</span>
        </footer>

      </body>
    </html>
  );
}
